{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:8082",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/polish": {
      "post": {
        "tags": [
          "text-polish-controller"
        ],
        "operationId": "polishText",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/PolishingRequestDto"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/PolishingResponseDto"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "PolishingRequestDto": {
        "type": "object",
        "properties": {
          "language": {
            "type": "string"
          },
          "domain": {
            "type": "string"
          },
          "content": {
            "type": "string"
          }
        }
      },
      "PolishingResponseDto": {
        "type": "object",
        "properties": {
          "polished_content": {
            "type": "string"
          },
          "similarity": {
            "type": "number",
            "format": "double"
          }
        }
      }
    }
  }
}